### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by alexandre** [estin/pomp#1]
I would like to know which license the project use. It helpls a lot, IMHO.

[ ]'s (hugs)

**Comment by sibelius** [comment]
http://opensource.org/licenses

**Comment by alexandre** [comment]
Better -> http://www.addalicense.com/add

**Comment by estin** [comment]
It is BSD license.
This repo is the mirror to bitbucket main repo.
App http://www.addalicense.com/add does not help add license.

**Comment by alexandre** [comment]
@estin ,

I'll fork the project to read and try to help. Thanks.

[ ]'s(hugs)

**Comment by estin** [comment]
@alexandre, feel free to contribute )
